### ISSUE TITLE
bixi station name encoding

### ISSUE THREAD

**Issue by lemieuxs** [eskerda/pybikes#109]
Hi,

I don't know if the issue happens in other providers, but I realized that a lot of station name coming from the "bixi.py" provider have encoding problems. 

For instance : '6002 - DÃ©zery/Ste-Catherine' (encoded in unicode) should be Saint-Urbain / René-Lévesque. The problem is probably in the page that the scrapper fetches and not directly in "pybikes", but if we could re-encode the string to get the proper accent it would be awesome !

Seems like when I encode the string in problem in latin1 everything is fine.

Thanks.

**Comment by eskerda** [comment]
I've been finding this issue with other providers too, so I think we introduced a bug somewhere. Let me check

**Comment by eskerda** [comment]
Weird, seems requests is defaulting to ISO-8859-1. That behavior was introduced on 2014, so not sure why it started affecting now. Still investigating, a quick fix is ready

**Comment by eskerda** [comment]
This should fix it: https://github.com/eskerda/pybikes/pull/110
