### ISSUE TITLE
Montreal Bixi data migration

### ISSUE THREAD

**Issue by f8full** [eskerda/pybikes#120]
It seems with the nice days coming up, Bixi made a few changes to the way data is served for Montréal.
In
https://github.com/eskerda/pybikes/blob/8d6654d49f1ad0ec5d940259c7fb9ebe77d3fb90/pybikes/data/bixi.json
Lines 12 and thirteen
    "feed_url": "https://montreal.bixi.com/data/bikeStations.xml", 
    "format": "xml"

Seem to now be invalid. (error 404 in a broswer). 
[EDIT] It seems the xml source came back online after a few hours, but the json is still up [EDIT END]

And replaced by a json feed at the following (still https) url
https://secure.bixi.com/data/stations.json
using some kind of letter based code to describe fields.
![image](https://cloud.githubusercontent.com/assets/416651/13711173/285a5cb2-e78b-11e5-9a6a-38557990714f.png)
> id: stationId (int)
> s : name (string)
> n : service number (int, 4 digits)
> st : ?? (int)
> b : ?? (bool)
> su : ?? (bool)
> m : ?? (bool)
> lu : last update (long int)
> lc : ??last station checkin?? (long int)
> bk : ??blocked?? (bool)
> bl : ?? (bool)
> la : latitude (float)
> lo : longitude (float)
> da ?? (int)
> dx : ?? (int)
> ba : ?? (int)
> bx : ?? (int)

Maybe it puts it more in line with some other systems with the same backend. I don't master python myself, but I'd be curious about the description of the fileds, as I pursue related open source project around this data, in Java
[See BixHistorique-2015](http://bixhistorique-2015.appspot.com/)

I see http://citybik.es serving results for Montréal, though.

Lemme know if I can be of further help, I hope I did enough, citybik.es API is a gift !

**Comment by eskerda** [comment]
Nice to hear the API is useful for BixHistorique!

Thanks for checking on the 404. Seems it's back. Will keep an eye on it once season reopens, maybe the xml stops being updated? I must guess they won't break with other spiders already parsing it so they put it back online. As of now, it will be easier to keep supporting the XML.

Funny thing, this JSON syntax is the same as http://bikeshare.ae/, if you are curious you can see it at [pybikes/adcb.py](https://github.com/eskerda/pybikes/blob/master/pybikes/adcb.py)

**Comment by f8full** [comment]
Thank you very much !

As a matter of fact, I do not use the API for BixHistorique, but I do in an other of my project, an android app (soon to be updated to v2.0 ;))
https://play.google.com/store/apps/details?id=com.ludoscity.findmybikes&hl=en

Thks again for pointing me in the right direction, I'll make good use of this rosetta stone.
