### ISSUE TITLE
Add Helsinki

### ISSUE THREAD

**Issue by eskerda** [eskerda/pybikes#128]
Possible endpoints:

- Smoove API: https://helsinki-fi-smoove.klervi.net/api-public/stations That one is still missing the data, but the format should be same as in the demo here: https://demo-v2.fr.smoove.klervi.net/api-public/stations
- OpenTripPlanner API (real list of stations, realtime status will be fetched from Smoove): http://beta.digitransit.fi/otp/routers/hsl/bike_rental

**Comment by tuukka** [comment]
Smoove API endpoint has changed at the last minute, and some of the first stations have appeared there already: http://helsinki-fi.smoove.pro/api-public/stations

**Comment by tuukka** [comment]
This system and both APIs are now operational.

**Comment by eskerda** [comment]
@tuukka 

We went for the Smoove feed, since it has total slots value and station id was easy to extract from the name. Hopefully, more smoove feeds will move to a public API, so we could reuse this code too.

Find an online feed at: http://api.citybik.es/v2/networks/citybikefinland-hsk
Most apps supporting the CityBikes API will now support the system too

A couple of questions:
- Is CityBikeFinland the correct name for the system?
- I added the following as companies holding the system. Is it correct?
```
      "Helsinki City Transport", 
      "Helsinki Regional Transport Authority", 
      "CityBikeFinland", 
      "Smoove SAS", 
      "Moventia"
```

**Comment by tuukka** [comment]
@eskerda Great to have you and all your API users onboard, thank you! CityBike Finland is the company that operates the system. I don't think the system has an official name, which is why the parties refer to it by many names. "Helsinki city bikes" might be clearest.

I got the recommendation from Smoove to change to using their newer API endpoint URL: http://helsinki-fi.smoove.pro/api-public/stations

In the response, `style: "CB"` means that the station has a payment card terminal for registering to the system.

**Comment by tuukka** [comment]
Regarding the list of companies, it's good as it is. If you wanted to shorten it, you could leave out Smoove and Moventia, as CityBike Finland is the company owned by them as a joint venture.

**Comment by eskerda** [comment]
@hugovk fixed the issue with the naming. I updated the tag too, so current feed is http://api.citybik.es/v2/networks/citybikes-helsinki and http://api.citybik.es/v2/networks/citybikefinland-hsk redirects to the new one too, in case someone was already reading from there.

Going to add the `cb` as an extra and we are good! Thanks @tuukka
