### ISSUE TITLE
"InsecureRequestWarning: Unverified HTTPS request is being made."

### ISSUE THREAD

**Issue by hugovk** [eskerda/pybikes#134]
pybikes gives an InsecureRequestWarning for Python 2.7.9 and Python 2.7.11 on Windows 7:

> InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. 

https://urllib3.readthedocs.io/en/latest/security.html#insecurerequestwarning

For example:

```python
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pybikes
>>> bikeshare = pybikes.get('citybikes-helsinki')
>>> bikeshare.update()
C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS
request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/late
st/security.html
  InsecureRequestWarning)
>>>
```

**Comment by eskerda** [comment]
Not all networks supported have valid SSL certificates (...)

Maybe we should do it the other way around. Set SSL verification by default, and disable it manually from spider.

**Comment by eskerda** [comment]
Found it. It is not a network, but a failure when using an https proxy:

https://github.com/eskerda/pybikes/commit/b1302a1518cb4d15fb88889dcbd310d4dc31c153

**Comment by hugovk** [comment]
Thanks, that's silenced it.

**Comment by eskerda** [comment]
Seems affecting network is veloway

```
In [1]: import pybikes
In [2]: scraper = pybikes.utils.PyBikesScraper()
In [3]: scraper.request('http://www.dkbus.com/cartoV3/libProxyCarto.asp')
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
```

**Comment by hugovk** [comment]
Actually, I re-tested incorrectly and it didn't silence it.

**Comment by hugovk** [comment]
Also, with latest master (Python 2.7.11, Win 7):
```python
>>> scraper = pybikes.utils.PyBikesScraper()
>>> scraper.request('http://www.dkbus.com/cartoV3/libProxyCarto.asp')
C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py:821: InsecureRequestWarning: Unverified HTTPS
request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/late
st/security.html
  InsecureRequestWarning)
u' <font face="Arial" size=2>\n<p>msxml3.dll</font> <font face="Arial" size=2>erreur \'80072ee2\'</font>\n<p>\n<font fac
e="Arial" size=2>Le d&#233;lai imparti &#224; l&#146;op&#233;ration est d&#233;pass&#233;\r\n</font>\n<p>\n<font face="A
rial" size=2>/cartoV3/libProxyCarto.asp</font><font face="Arial" size=2>, ligne 16</font> '
>>>
```

When I visit http://www.dkbus.com/cartoV3/libProxyCarto.asp in the browser it redirects to https://www.dkbus.com/cartoV3/libProxyCarto.asp and shows the same error:

> msxml3.dll erreur '80072ee2'

> Le délai imparti à l’opération est dépassé

> /cartoV3/libProxyCarto.asp, ligne 16

The console says:

> Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by eskerda** [comment]
Yes, dkvelo is broken. A fix is in progress
