### ISSUE TITLE
Add history functionality

### ISSUE THREAD

**Issue by tuukka** [eskerda/pybikes#138]
Do you know an implementation or have ideas for functionality based on the continuously scraped station data? It could be used to draw "spark lines" of the recent bike availability history at simplest, all the way to predicting bike availability in the future.

**Comment by eskerda** [comment]
We stored historical data for a period of time until something broke our OVH servers on Aug. 2015. Since then we are meaning to do something about this, mainly:

1. Find a better way (and place) to store historical data.
2. Release monthly dumps (instead of storing it all).
3. Release all old dumps

**Comment by noussan** [comment]
Any news about this topic? Thanks.

**Comment by eskerda** [comment]
No news insofar. No historical data will be stored until we find a way to sustain the project. The project has enough costs as it is ATM.
