### ISSUE TITLE
timestamp: api returns "2016-04-29T01:24:Z" instead of "2016-04-29T01:24:00.000Z"

### ISSUE THREAD

**Issue by tuxayo** [eskerda/pybikes#141]
I was importing a bunch of stations data and had an error about date parsing.
After listing all the date string where being imported

```
...
2016-04-29T01:23:59.999Z
2016-04-29T01:24:Z
2016-04-29T01:24:00.001Z
...
```
I found the culprit .

It seems that it does not comply with ISO 8601.
https://jsfiddle.net/wq7tjec7/14/

It should be
2016-04-29T01:24:00Z
or
2016-04-29T01:24:00.000Z
or
2016-04-29T01:24Z

(according to this random validator that I've found ^^)

**Comment by eskerda** [comment]
I think I found the problem. There's an rstrip of zerores on datetimes on the api, hence any date with 0 on seconds will become nothing: https://github.com/eskerda/citybikes-api/blob/master/api/models.py#L116

Moving this issue there
