### ISSUE TITLE
Łódzki Rower Publiczny (Łódź) bike share network have no country

### ISSUE THREAD

**Issue by rousseauo** [eskerda/pybikes#143]
Missing contry Łódź netwok
Country is PL (Poland)

`{"company":"Nextbike GmbH","href":"/v2/networks/lodzki-rower-publiczny","id":"lodzki-rower-publiczny","location":{"city":"Łódź","country":null,"latitude":51.7592485,"longitude":19.4559833,"bounds":{"maxLat":52.65794718430512,"minLat":50.860549815694874,"maxLng":20.904314098754437,"minLng":18.007652501245563,"maxElev":10000,"minElev":10000}},"name":"Łódzki Rower Publiczny","timestamp":null}`

**Comment by eskerda** [comment]
Fixed in https://github.com/eskerda/pybikes/commit/944d5468f7ce1be25ddc8f0ec0e4e18569697338
