### ISSUE TITLE
Feature request: scrape "Bycyklen" from Copenhagen, DK

### ISSUE THREAD

**Issue by lbschenkel** [eskerda/pybikes#163]
The stations are listed here:
https://bycyklen.dk/en/find-a-bycykel/

It's possible to get a JSON structure with all stations by doing a GET:
https://bycyklen.dk/umbraco/Surface/BookingSurface/GetStationsList

Unfortunately the list above does not include the number of available bikes and I didn't find a way yet to scrape that. I'll comment here if I find out more.

I don't know Python so I'm afraid that implementing a new scraper from scratch is beyond my current skills.

**Comment by eskerda** [comment]
Seems like availability can be found at:

```
curl 'https://bycyklen.dk/en/my-account/my-reservations/book-cykel-via-website/'  --data 'lat=55.673582&lng=12.564984&page=0' -H 'X-Requested-With: XMLHttpRequest'
```

And from there, iterating over pages. It might not be trivial to correlate that to the feed. Either by closest distance to the marker (each availability contains a static map), or by similarity on name.

**Comment by eskerda** [comment]
I also see their "android app" is just the same website adapted to the layout, so no luck on there for reverse engineering anything.

**Comment by eskerda** [comment]
> I don't know Python so I'm afraid that implementing a new scraper from scratch is beyond my current skills.

It's true this spider might get a bit tricky. However do not overestimate the task, in the end all spiders are the same.

Either you can give it a try and I will review it, or I can do it and you review it so next time you know how you would do it?

**Comment by lbschenkel** [comment]
I can actually try implementing it, it'll be a good excuse to learn Python — however I believe that it'll take a while since I'm not going to have a lot of free time in the foreseeable future.

In case you prefer to do it, I don't mind at all — I am more interested that this data becomes available as soon as possible than in who actually implements it.

**Comment by eskerda** [comment]
> In case you prefer to do it, I don't mind at all — I am more interested that this data becomes available as soon as possible than in who actually implements it.

Sure. It's also not available at http://data.kk.dk/ so adding this might make them rethink and provide a good feed.

Will leave the issue open and whoever takes it first does it
