### ISSUE TITLE
Mobi / Vancouver Bike Share

### ISSUE THREAD

**Issue by bcaller** [eskerda/pybikes#179]
New bike network.
Probably best to wait a few weeks as they may be still developing it.
https://www.mobibikes.ca
Currently all data is within the HTML.

**Comment by mountainMath** [comment]
Here is a shadow API pulling the data out of the html and cleaning it a bit (removing duplicate stations, but still leaving the bike rentals in the feed): http://mountainmath.ca/mobi/stations

Feel free to use, but might break when mobi changes their website. Shadow API updates once a minute, but mobi data seems to update quite a bit slower. Built for http://mountainmath.ca/mobi

**Comment by gapple** [comment]
I made a guess based on the API URL in #128, and it looks like http://vancouver-ca.smoove.pro/api-public/stations works

**Comment by mountainMath** [comment]
Cool. Great find, thanks for the info!

**Comment by eskerda** [comment]
Fixed in https://github.com/eskerda/pybikes/pull/188
