### ISSUE TITLE
Replace pyquery for lxml

### ISSUE THREAD

**Issue by eskerda** [eskerda/pybikes#18]
Newest modules will use lxml, for the ones already using pyquery, we should just stay with lxml (pyquery is just a wrapper around it).

pyquery is nice enough, but there's no need to have one extra dependency now that we are friendly with lxml

**Comment by hugovk** [comment]
This issue can be closed.

> We couldn’t find any code matching 'pyquery'

https://github.com/eskerda/pybikes/search?utf8=%E2%9C%93&q=pyquery

**Comment by eskerda** [comment]
True, even he package is not on requisites anymore.
