### ISSUE TITLE
New standard network fields required.

### ISSUE THREAD

**Issue by rolinger** [eskerda/pybikes#180]
I also think there should be some new standard fields that are returned with the basic "network" query.

There should be : 
vendorURL: 'http://www.bikevendor.com',
vendorIOS: 'http://appstore.apple.com/vendorID=bikeVendor',
vendorAndroid: 'http://playstore.appl.com/vendorID=bikeVendor',
deeplinkIOS: 'bikevendor://?',
deeplinkAndroid: 'com.bikevendor.android?'

I literally just went through and retrieved 40+ vendor URLs....ALL have apps, but I don't know if any of them have deeplinks.  But to collect this data is researching 40+ vendor URLs, 40+ app store appIDs, 40+ playstore appIDs, 40+ ios deeplinks, 40+ android deeplinks (if either of those last two even exist).

This data should be coming from the api, provided by the individual vendors...not something we have to go track down and check every few days to see if there any new vendors and then manually go retrieve those new vendors information.

**Comment by eskerda** [comment]
I do agree about vendor urls. Why iOS and Android links though?

> This data should be coming from the api, provided by the individual vendors...not something we have to go track down and check every few days to see if there any new vendors and then manually go retrieve those new vendors information.

Whatever metadata is wanted can be added to either the data files or the actual python implementation of the spider. You have the repo here. It seems to me that if you are already manually retrieving this information to include somewhere, you may as well contribute it to the project.

**Comment by rolinger** [comment]
correct...however I have never contributed to a project before.  But am glad to contribute this data.  Just need to know how.  The only downside is I only manually retrieved this data for all the US based bikeshares (40+)....which doesn't come close the 400+ total bikeshares the api represents.  :(   But it is a start.

**Comment by rolinger** [comment]
for iOS/Android links:

Example:  my app displays bike data for any city if a bike share exists in that city, but if a user doesn't have the bike vendors app, or know where to go get it, then it becomes a more complicated process for the user. If we are able to readily provide them those links...or check to see if the app already exists on their phone ...then (as an example) my app can direct them to where they need to go or auto-launch that vendors app (assuming the user already has it).

**Comment by eskerda** [comment]
From https://github.com/eskerda/pybikes/issues/155

> my apologies...not trying to offend here. I guess I don't fully understand how all the data is being assembled. My assumption was a vendor would register the api site and this project would pull from their own listings. Thus it would be (easier) to have the vendors add in or standardize the fields to meet this api's requirements. From your comments though, I think my above assumption is wrong.
> 

We are completely unrelated to vendors. Some of them show interest on appearing on the API or even contribute a patch supporting their system, but that's a big minority of them. We started this project as a way to motivate vendors and city councils to provide this information when we found none whilst creating an Android app. We do not create an android app anymore, since there are many great apps out there, some of which are FOSS. Currently, this project lives on free time, which is the most expensive one.

> I have assembled all the above data. I would be happy to contribute in all my data...I guess the initial manual data grab sucks, but after that it should be easy to maintain or easy to update with new vendors.
> 
> For the links to iOS/Android apps reason: my app displays bike data for any city if a bike share exists in that city, but a user doesn't have the bike vendors app, or know where to go get it, then it becomes a more complicated process for the user. If we are able to readily provide them those links...or check to see if the app exists...then (as an example) my app can direct them to where they need to go or auto-launch that vendors app (assuming the user already has it).
> For the record...this is a GREAT project and I can tell a lot of work has gone into it. I am glad to help in anyway I can.

Rethinking it, most probably any information is good information, so feel free to discuss how can we add these fields and I will gladly help.

**Comment by eskerda** [comment]
As for how to add this information:

Any information present on the datafiles under meta, will be available to network instances, and therefore to the API, see any json file under [data/](https://github.com/eskerda/pybikes/tree/master/pybikes/data)

If it's a constant on the same schema (see: https://github.com/eskerda/pybikes/blob/master/pybikes/cyclocity.py#L35), it can be added to the actual class implementation under meta too.

**Comment by rolinger** [comment]
wow...yeah, I def had it backwards.  This is even a more monumental effort than I originally thought.  Manually reverse engineering all the vendor's APIs and then trying to standardize all those vendors.  one to many....versus many to one.  What a huge effort.  

So does each vendor have its own specific python script that needs to be updated?  Or is there a secondary script (or be created) that can parse my json and auto-add these extra fields to all the necessary files?

Here is a sample of the json I am creating.  I first export all name/IDs from "/networks" then create a json file.  After that I manually grabbed each vendor name, googled it, copied their url then search their site for the app links.  Haven't even gotten to the deeplinks yet.  So far, only 42 US cities.  

	name:'Capital BikeShare',	{
		cbID:'capital-bikeshare',
		myAppID:0,
		url:'https://www.capitalbikeshare.com',
		appstore:'https://itunes.apple.com/us/app/spotcycle/id323382862?mt=8',
		playstore:'https://play.google.com/store/apps/details?id=com.eightd.android.spotcycle&hl=en',
		iosDeeplink:'',
		androidDeeplink:''
	},
