### ISSUE TITLE
Atlanta Bike share

### ISSUE THREAD

**Issue by mmccoy37** [eskerda/pybikes#185]
local website is http://relaybikeshare.com/
powered by http://socialbicycles.com/

Tried to find an endpoint with json info from http://relaybikeshare.com/ but didnt find any info.

**Comment by edumucelli** [comment]
Related to #39.

**Comment by eskerda** [comment]
@edumucelli is it? I can't find it at https://github.com/NABSA/gbfs/blob/master/systems.csv nor main website lists any meta tag pointing to the gbfs feed

**Comment by edumucelli** [comment]
@eskerda, my bad, it is not, gonna remove the link.

**Comment by eskerda** [comment]
Was added on the gbfs batch
