### ISSUE TITLE
Old docs need update

### ISSUE THREAD

**Issue by anastmag** [eskerda/pybikes#186]
The Description of the module needs update in __init__.py file. It's not functional at the moment.

copied from __init__.py 

> PyBikes is a parsing library to extract bike sharing information from multiple
> sources. It contains multiple classes to handle this sort of information,
> and is not a class itself. The idea is to be able to call it like:
> from pybikes import BicingShareSystem, BicingStation
> bicing = new BicingShareSystem() <- Returns BicingShareSystem
> print "%s: %s" % ("Bicing City is", bicing.meta.city)
> stations = bicing.get_stations() <- Returns Array[BicingStation]

**Comment by eskerda** [comment]
Fixed at https://github.com/eskerda/pybikes/commit/0f596682e1d695bd5b38f4428b25424eb26678c9

I guess no docstring is better than one with errors.

**Comment by anastmag** [comment]
Lol
