### ISSUE TITLE
Check domoblue feeds

### ISSUE THREAD

**Issue by eskerda** [eskerda/pybikes#202]
Lots of feeds on domoblue seem inactive. Check which are inactive for the season and which ones have actually cease to exist.

http://www.onroll.info/p/mapa.html

https://github.com/eskerda/pybikes/pull/201

**Comment by sbssk8** [comment]
Hey!

I tried to call to domoblue (the company behind onroll systems) to ask it they had any of the networks available and it seems like the phone number doesn't exist anymore... After further checking, it seems like the company faced bankruptcy [0] back in 2019... 

[0]: https://www.boe.es/diario_boe/txt.php?id=BOE-B-2019-2771  (In Spanish)

**Comment by eskerda** [comment]
@sbssk8 thanks for the info! Certainly it looks like domoblue went under long ago. Even if it was plausible that some systems might still be running under another company or by the city council, I have checked and all the stations report "No Service", so that validates it.

**Comment by sbssk8** [comment]
Great! I started investigating after seeing all the stations for onroll networks were not online
Thanks for removing them on https://github.com/eskerda/pybikes/pull/509 !
