### ISSUE TITLE
Nextbike provider

### ISSUE THREAD

**Issue by AdrienGiboire** [eskerda/pybikes#22]
I'm not sure it's the right place but I'm wondering if Citybik.es provides data from Nextbike (http://www.nextbike.net/)? I don't really know how to find out by myself…

**Comment by eskerda** [comment]
Ok, now that we are not going to flood nextbike servers with unnecessary requests, we can actually add most nextbike networks.

**Comment by eskerda** [comment]
We currently support 108 nextbike networks. If anything relevant is missing, feel free to open a ticket or a PR about it.
