### ISSUE TITLE
Add Divvy in Chicago, IL, USA

### ISSUE THREAD

**Issue by brandongalbraith** [eskerda/pybikes#224]
https://feeds.divvybikes.com/stations/stations.json

**Comment by edumucelli** [comment]
@brandongalbraith, refer to https://github.com/eskerda/pybikes/blob/master/pybikes/data/gbfs.json#L327

**Comment by eskerda** [comment]
Yep, network is already supported https://api.citybik.es/v2/networks/divvy

**Comment by brandongalbraith** [comment]
Whoops, sorry about that folks!
