### ISSUE TITLE
Missing pods for "Bycyklen" in Copenhagen 

### ISSUE THREAD

**Issue by JulietaMarcos** [eskerda/pybikes#226]
https://api.citybik.es/v2/networks/bycyklen is returning an empty list of stations (or sometimes just 1), but there're actually 104 stations: https://bycyklen.dk/umbraco/Surface/BookingSurface/GetStationsList

**Comment by eskerda** [comment]
Seems the feed we are using has incorrect lat / lngs

http://my.bycyklen.dk/da/reservations/dockingstationsinfoxml

**Comment by eskerda** [comment]
Thanks for reporting, should be fixed by now. Changes will go upstream to the API in some minutes.

**Comment by fede843** [comment]
wow, that's fast. I'll try it and report result

**Comment by eskerda** [comment]
TripGO? Remember to read the ToS https://api.citybik.es/v2/#tos

**Comment by nighthawk** [comment]
Yep, thanks for the reminder — we definitely want to spread the word! We already link to it from our website and will link to it from the apps soon in an update that adds support for real-time bike share info.
