### ISSUE TITLE
T-Bike data source

### ISSUE THREAD

**Issue by kiang** [eskerda/pybikes#231]
T-Bike is a bike sharing service provided by Tainan City Government, Taiwan. Maybe you would like to have it in the pool, too.

JSON format for stations: http://tbike.tainan.gov.tw:8081/Service/StationStatus/Json

Opendata dataset information: http://data.tainan.gov.tw/dataset/t-bike
Major website: http://tbike.tainan.gov.tw/Portal

**Comment by anastmag** [comment]
Working on it.

**Comment by Altonss** [comment]
The link with the json feed is still working, so if I have time, I will have a look to implement it :)

**Comment by Altonss** [comment]
ping @eskerda 
In the feed there is the name of station and the address in chinese and in english, which one should I pick for pybikes or is there a way to have both?

**Comment by eskerda** [comment]
I am not sure on what would be best. Most of the times the approach has been to take the closest language to the place where the system is (the contrary would be unrespectful to a local using the data). If there's data available in english, you can include it in extra, for instance could be under

```
{
    "name": "name in chinese",
    ...
    "extra": {
        ...
        "en": { "name": "name in english", "address": "address in english" },
    }
}
```
