### ISSUE TITLE
Movete parser shouldn't use eval on third party code

### ISSUE THREAD

**Issue by flebel** [eskerda/pybikes#241]
This use of `eval` to parse a feed's JavaScript array into a Python list is extremely unsafe:
https://github.com/eskerda/pybikes/blob/c2f2fb6ad619521150bc41c6fe18ac6564bfa831/pybikes/movete.py#L31

There are other uses of `eval` in this project but none of them evaluate third party code:
https://github.com/eskerda/pybikes/search?utf8=%E2%9C%93&q=eval&type=

**Comment by eskerda** [comment]
Yup, `ast.literal_eval` seems the way to go.

**Comment by eskerda** [comment]
Thanks for reporting @flebel !
