### ISSUE TITLE
Add 'Züri rollt'

### ISSUE THREAD

**Issue by habi** [eskerda/pybikes#253]
Add https://www.stadt-zuerich.ch/aoz/de/index/shop/veloverleih/standorte.html

**Comment by habi** [comment]
I don't know about an open API, but at least there's an app: http://www.engineerit.ch/apps/veloverleih/#app

**Comment by Manu1400** [comment]
it's not exist now...
We can close this issue.

**Comment by eskerda** [comment]
Covered by publibike https://github.com/eskerda/pybikes/blob/d3a831fc8bba27eaaefc917b2e071fc518e69ef9/pybikes/data/publibike.json#L3-L13
