### ISSUE TITLE
Add Swiss Cargo bike share carvelo2go

### ISSUE THREAD

**Issue by habi** [eskerda/pybikes#254]
https://www.carvelo2go.ch, the biggest Swiss cargo bike sharing platform is missing.

**Comment by martgnz** [comment]
Seems like this system doesn't really work with docks, rather you pick the bikes at a shop or business, is that right? Adding support would be tricky and not sure if it can be done without a wider refactor of the data format.

**Comment by habi** [comment]
Absolutely correct, these cargo bikes are usually picked up at a "host".
If that's not implementable, then the issue can be closed.
