### ISSUE TITLE
Add Whitebikes bike sharing system

### ISSUE THREAD

**Issue by andrewshadura** [eskerda/pybikes#258]
Please add [Bratislava bike sharing system](http://whitebikes.info/), and possibly more based on the same code: http://opensourcebikeshare.com/

**Comment by eskerda** [comment]
Last I heard from opensourcebikeshare they told me they were planning on supporting the GBFS specification. I guess this is not out there yet.

For reference, this is the current feed http://whitebikes.info/command.php?action=map:markers

**Comment by andrewshadura** [comment]
So, is it difficult to support?

**Comment by eskerda** [comment]
Not at all, seems like a pretty standard JSON feed

**Comment by edumucelli** [comment]
Added it.
