### ISSUE TITLE
bicincitta.tobike.it endpoints no longer available

### ISSUE THREAD

**Issue by valerio-varriale** [eskerda/pybikes#262]
All the endpoints in the file /data/bicincitta.json at the domain bicincitta.tobike.it answer with a "301 Moved Permanently" to the URL "http://www.bicincitta.com"

For the cities of Trento (tag "e-motion-trento"), Rovereto (tag "e-motion-rovereto") and Pergine Valsugana (tag "e-motion-pergine-valsugana") there are three json dataset indexed at the site "OpenData Trentino" edited by "Provincia autonoma di Trento - Servizio Trasporti"
http://dati.trentino.it/dataset/stazioni-bike-sharing-emotion-trentino

- [Rovereto](http://dati.trentino.it/dataset/stazioni-bike-sharing-emotion-trentino/resource/0755cb74-4d97-470b-96ef-d4f5ccb34c8e)
- [Trento](http://dati.trentino.it/dataset/stazioni-bike-sharing-emotion-trentino/resource/b5242797-fe4e-4687-a471-2662d2cb8f8d)
- [Pergine Valsugana](http://dati.trentino.it/dataset/stazioni-bike-sharing-emotion-trentino/resource/ffaa1b8e-4074-4523-8aa6-d0a7977fc08d)

These dataset have a "Creative Commons Attribution 4.0" license.

I am sorry, I know of no alternatives for the other cities.
 Valerio Varriale

**Comment by eskerda** [comment]
I think a refactor is possible by matching network and city names within pybikes to this index http://www.bicincitta.com/frmCercaComune.aspx

Will work on that
