### ISSUE TITLE
Bay Area Bike Share Has Corporate Sponsor, Now "Ford GoBike"

### ISSUE THREAD

**Issue by coneybeare** [eskerda/pybikes#269]
They have a new domain https://member.fordgobike.com/map/ and new stations which are not currently being reflected in pybikes network 'bay-area-bike-share'

**Comment by flebel** [comment]
https://github.com/eskerda/pybikes/pull/267

**Comment by robbiet480** [comment]
The BABS GBFS is also dead now.

**Comment by eskerda** [comment]
@robbiet480 did some magic :)
