### ISSUE TITLE
Missing Italian Bike Sharing systems 

### ISSUE THREAD

**Issue by traversaro** [eskerda/pybikes#28]
Hi @eskerda ! 
@xrmx mentioned on Twitter that he could be interested (not at the moment, but in the future) in adding some scrapers for bike sharing systems in Italy that are not based on Bicincittà system and that are not present in PyBikes. 
I had some old notes on the Bike sharing systems that have websites that are suitable to scrape, but I had never the time to implement a scaper for this systems. @xrmx thought I could share this information here, so anyone interested in implementing a scaper could find an easy list of system suitable for writing a scraper.
- [x]  BikeVerona (Verona) : https://www.bikeverona.it/stationsmap
- [ ]  BKWare (Now powering just Riva del Garda, it was used by Trento but it seems that they switched to Bicincitta')   : http://riva.unbit.it/
- [ ] Maglie In Bici (Maglie, now offline?) : http://www.maglieinbici.it/
- [x] Bike Sharing Napoli (Napoli) : http://www.bikesharingnapoli.it/en/mappa-stazioni/

In particular the BKWare system is quite cool because it provides information on every single bicycle.

Some existing indipendent systems are now being migrated to Bicincitta', so I guess It's also time for an update to the Bicincitta' metadata as suggested  in https://github.com/eskerda/PyBikes/issues/19 .

**Comment by njoylab** [comment]
Hi,
Napoli just went out of beta

This is the endpoint their app is using for a JSON response
http://www.movinap.it/_CI/api_v1/station/getAllStationsInfo

I'm not really into python, but if nobody wants to implement it I could try maybe with some suggestions on the project.

Best

**Comment by eskerda** [comment]
Hey, thanks for the info. Just added the system on the referenced commit.

Feed available at http://api.citybik.es/v2/networks/bike-sharing-napoli

**Comment by njoylab** [comment]
Hi @eskerda 
Bike Sharing Napoli is asking me if it's possible to hide the "demo"  stations
CleaNap demo LumiLab
CleaNap demo 2
CleaNap demo 3

I suppose that everything with "demo" in the name could be skipped.
I could prepare a pull request if you don't have time

Thanks!

**Comment by eskerda** [comment]
Hmmmmm..... yes but, wouldn't that be the job of Bike Sharing Napoli itself?


- Y no olviden vitaminarse y supermineralizarse!

**Comment by njoylab** [comment]
You are definitely right. 
I answered them asking not to send those stations,but I don't think they will do it.. 
let's see

**Comment by Altonss** [comment]
Bikeverona has a working gbfs feed here: https://gbfs.urbansharing.com/bikeverona.it/gbfs.json so this could be integrated easily, we just need to handle correctly the bikes with childseats as it has been done for Bikemi (Milano, IT) in #456 :)
