### ISSUE TITLE
Add others system in Brazil

### ISSUE THREAD

**Issue by arrobaraujo** [eskerda/pybikes#287]
http://www.integraufrj.com.br/mapaestacao.aspx - Another system in Rio de Janeiro
http://www.bicicletaintegrada.com/mapaestacao.aspx - Another system in Fortaleza, Ceará
https://manobike.tembici.com.br/mapaestacao.aspx - Manaus, Amazonas
http://www.bikevitoria.com/mapaestacao.aspx - Vitória, Espírito Santo
https://udibike.tembici.com.br/#mapa-das-estacoes - Uberlândia, Minas Gerais
https://danoninhobikekids.tembici.com.br/mapaestacao.aspx - kids system in Santos, São Paulo
https://estacaounimedjf.tembici.com.br/ - Juiz de Fora, Minas Gerais (Stations map is on home page)

**Comment by edumucelli** [comment]
@eskerda I can take some of those.

**Comment by eriickaraujo** [comment]
https://www.bikevv.com.br/mapa-das-estacoes/ - Vila Velha, Espírito Santo

**Comment by martgnz** [comment]
All these urls return 404 but Vitória, which I implemented in https://github.com/eskerda/pybikes/pull/655. Do you know more systems we could add in Brazil? Otherwise, this could be closed.
