### ISSUE TITLE
Add Bicilascondes (Chile) data

### ISSUE THREAD

**Issue by sergiolucero** [eskerda/pybikes#288]
People, I would love to see this data included. I've been mining it for some time now. https://www.bicilascondes.cl/availability_map/getJsonObject

It is not available on pybikes, it provides live counts of bikes/slots available and OPN/CLS station status, as well as nearbyStations (though only for some stations). I've used the data gathered over the last two months to produce clusters of stations as insight into their shortcomings: [clusters](http://www.quant.cl/static/blc_clusters.jpg)
If anyone's interested, I'd like to compare and have a discussion about what it means to have a decent public bike system (ie: how many broken stations are acceptable as a percentage?).

**Comment by eskerda** [comment]
@sergiolucero Cool graphs. Unfortunately, it would be more interesting to know how many broken bikes, compared to broken stations for this case study. 
If you find anything maybe it makes sense to write a blog post, definitely interested.
