### ISSUE TITLE
Update sharing system 'bike recife' from Pernambuco, Brazil

### ISSUE THREAD

**Issue by igormatos** [eskerda/pybikes#289]
The site is using the data from the old system (http://bikepe.com.br), now it is https://bikeitau.com.br/.
The company that was involved was Samba and Serttel, now is Tembici.

**Comment by eskerda** [comment]
Related to https://github.com/eskerda/pybikes/pull/280, probably same fix

**Comment by eriickaraujo** [comment]
In this site we have the information for the new system in Rio de Janeiro and São Paulo too

**Comment by eriickaraujo** [comment]
@igormatos perfeito! :D se não fosse pedir demais da sua gentileza, poderia fazer o mesmo com Salvador e POA? Já estrearam o sistema novo também. :)

**Comment by igormatos** [comment]
@eriickaraujo eu ia fazer isso, porém não consegui descobrir a url da API desses dois serviços ainda, talvez seja por que são recentes. Qualquer coisa te aviso, beleza?

**Comment by eriickaraujo** [comment]
Perfeito! Muito obrigado :) Aproveitando, eu abri alguns outros "issues" aqui, quando possível, você poderia checar eles, @igormatos ? :D

**Comment by igormatos** [comment]
Issue closed by PR #315

**Comment by igormatos** [comment]
@eriickaraujo a API do de Salvador e o de POA não estavam pegando de fato, mas tentei as mesmas urls hoje e funcionou.. já mandei PR com essa atualização. Agora esses outros eu vou ver depois 👍
