### ISSUE TITLE
Move Lille to open data feed

### ISSUE THREAD

**Issue by eskerda** [eskerda/pybikes#293]
It seems Keolis changed sites. For the system of Lille, there's the following open data feed available.

https://opendata.lillemetropole.fr/explore/dataset/vlille-realtime/information/
https://opendata.lillemetropole.fr/api/records/1.0/search/?dataset=vlille-realtime&facet=libelle&facet=nom&facet=commune

**Comment by mvanwijnendaele** [comment]
Has the open data feed been moved properly https://opendata.lillemetropole.fr/api/datasets/1.0/vlille-realtime/ ? Bike Sharing Atlas.org is not showing Lille so it seems there is an issue.

**Comment by Altonss** [comment]
It still doesn't seem to work :/ Is it easy to fix the issue?
