### ISSUE TITLE
Outdated station information for Call a Bike (Germany)

### ISSUE THREAD

**Issue by Lesik** [eskerda/pybikes#295]
I have checked daily during the past days, and the information on citybik.es is always wrong compared to the [Call a Bike website](https://www.callabike-interaktiv.de/de/rad-finden). Stations that contain bikes are shown as empty, and those that are empty show as having bikes available.

To see yourself, simply zoom in on any city (for example Frankfurt), and compare both maps.

**Comment by eskerda** [comment]
Fixed by https://github.com/eskerda/pybikes/pull/624
