### ISSUE TITLE
New velib

### ISSUE THREAD

**Issue by Bahjesaispas** [eskerda/pybikes#299]
New update for the .json file in paris. 

The new adress seems to be this one : https://www.data.gouv.fr/fr/datasets/velib-2-disponibilite-en-temps-reel/#_

The old one doesnt work anymore and JcDecaux is remplaced by Smoove.

**Comment by eskerda** [comment]
There's also this feed https://velib-metropole-opendata.smoove.pro/opendata/Velib_Metropole/station_status.json that should be GBFS but doesn't exactly comply with the standard fields.

**Comment by Phyks** [comment]
Hi,

Is anyone already working on this? I can have a look and make a MR to this repo else, as I already have to write some code for the new Velib API.

I have been dumping regularly data from the Velib API for the past 2 years with custom code, and just discovered pybikes. As I have to rewrite my own code anyways, I am thinking about moving to pybikes and contributing this :)

**Comment by Phyks** [comment]
Actually, both API endpoints mentionned above (https://velib-metropole-opendata.smoove.pro/opendata/Velib_Metropole/station_status.json and https://opendata.paris.fr/explore/dataset/velib-disponibilite-en-temps-reel/information/) report only part of the infos (typically, there is no info about which proportion of bikes is manual and which proportion is electric).

https://www.velib-metropole.fr/webapi/map/details?gpsTopLatitude=49&gpsTopLongitude=2.85&gpsBotLatitude=48.7&gpsBotLongitude=2&zoomLevel=19 is the API used by the official website and does contain all the available info, although there is no clear license for these data :/

**Comment by Bahjesaispas** [comment]
I've asked on twitter if we can use the official website information instead the open data. Waiting for an answer...

**Comment by Phyks** [comment]
Same here for a month now :/

**Comment by eskerda** [comment]
It's alright to use it. I would prefer to use the GBFS feed to avoid creating yet another implementation, but if it's missing data then why not go full in and get the feed with more info

**Comment by eskerda** [comment]
> Anyways, that's the best data available for now, so I'd rather use them as well. How would you handle the electric bikes vs standard bikes thing? I guess bikes should be the sum of the two, but how would you keep track of this detailed info (having citybik.es and apps that use it in mind)?

Other systems already have this. Not really happy on the syntax, but I guess it works. For the `smartbike` system, we have:
* `has_ebikes` => `true`
* `extra['ebikes']` => number of e-bikes on the station

**Comment by Phyks** [comment]
#300 should be implementing this. Let me know if you have any comments about this PR. :)
