### ISSUE TITLE
Add mobike (China, Italy, France, UK)

### ISSUE THREAD

**Issue by innovimax** [eskerda/pybikes#304]
https://mwx.mobike.com/mobike-api/rent/nearbyBikesInfo.do

**Comment by rebecca-palmer** [comment]
In addition to the above issue with dockless systems, it's unclear whether this is legally a public API: [it checks User-Agent](https://github.com/alulsh/dc-bikeshare-by-neighborhood/issues/1), and Mobike's general terms of service prohibit scraping/data mining [at least in the UK - term 5e](https://www.mobike.com/uk/).

**Comment by Altonss** [comment]
This service doesn't seem to exist anymore, at least their website seems broken, so we could maybe close this issue unless someone found a working API?

**Comment by mirh** [comment]
https://github.com/mobikeapp/mobike-api ?
