### ISSUE TITLE
San Diego DecoBike showing station info for Miami's City Bike

### ISSUE THREAD

**Issue by rolinger** [eskerda/pybikes#306]
Hi...I came across an issue that I thought was due to my coding, but it turns out every single Lat/Lon data for San Diego's Decobike is wrong.  The vendor info for Decobike (city, lat/lon) all appears correct - its just the individual station Name/Addresses and Lat/Lon all appear to be valid bike hub addresses in Miami for City Bike locations.

Every lat/lon is pretty much the same:   The network call is returning 99 stations, I sort them in order of a calculated distance to where a user's starting point is.  Below are the first and last of those 99 sorted by lat/lon distances to the user:

```
station: 0,
latitude:25.76624
longitude:-80.20121
name:"569 - NW 1st St & 1st Ave"
...
...
station:98,
latitude:25.7653275
longitude:-80.1313248
name:"101 - Inside South Pointe Park"
```

How can we get this data corrected?  Is this something being fed by Decobike and they need to be contacted or is this possibly merged data within citybik.es?

**Comment by johnsintal** [comment]
Decobike San Diego, San Diego, CA is showing bikes in Miami and not San Diego, could this be fixed please?
