### ISSUE TITLE
add Cykl (OpenSourceBikeShare)

### ISSUE THREAD

**Issue by ewooonk** [eskerda/pybikes#307]
I would like to add my local bike share network to the following file. 

https://github.com/eskerda/pybikes/blob/master/pybikes/data/open_source_bike_share.json
```
       {
            "tag":"Cykl",
            "meta":{
                "latitude":51.974000,
                "city":"Wageningen",
                "name":"Cykl",
                "longitude":5.667100,
                "country":"NL"
            },
            "feed_url":"https://www.cykl.nl/command.php?action=map:markers"
        }
```

**Comment by eskerda** [comment]
Feel free!

Need any help with that?

**Comment by ewooonk** [comment]
@eskerda 

I use the same backend as Whitebikes from Bratislava, therefore Python script below should work fine.

I also created a pull request for the pybikes/data JSON file.

https://github.com/eskerda/pybikes/blob/master/pybikes/open_source_bike_share.py

**Comment by eskerda** [comment]
Added by https://github.com/eskerda/pybikes/pull/308
