### ISSUE TITLE
"Stadtrad" network not updated for a year

### ISSUE THREAD

**Issue by jlwin** [eskerda/pybikes#310]
Hey everyone, I saw that the "Stadtrad" network data has not been updated for over a year now:
https://api.citybik.es/v2/networks/stadtrad
Last update: 2017-02-22
Any help, comments, findings, commits to solve this issues are highly appreciated.

**Comment by 4goettma** [comment]
"This API is a display layer of PyBikes." (https://api.citybik.es/v2/)

There is an issue for StadtRad Hamburg: https://github.com/eskerda/pybikes/issues/125

**Comment by Altonss** [comment]
I think this issue can now be closed, the Stadtrad Hamburg is now updated (but there is a small bug in the data that needs to be adressed!
