### ISSUE TITLE
Use GBFS feed for Bixi Montréal system

### ISSUE THREAD

**Issue by f8full** [eskerda/pybikes#311]
The feed is available here : https://api-core.bixi.com/gbfs/gbfs.json

source : https://www.bixi.com/en/open-data

**Comment by f8full** [comment]
WIP : https://github.com/f8full/pybikes/commits/master

**Comment by f8full** [comment]
And the PR (sry if there was a way to automagically link everything)
https://github.com/eskerda/pybikes/pull/312

**Comment by eskerda** [comment]
Great! Issues that come together with PR that fix them are the best, so this is greatly appreciated. Thanks!
