### ISSUE TITLE
Invalid longitude for nextbike pz/zabrzanski-rower-miejski-zabrze

### ISSUE THREAD

**Issue by rytilahti** [eskerda/pybikes#328]
The longitude for nextbike's zabrzanski-rower-miejski-zabrze ('204.917') is outside the regular (-180 - + 180) range, see https://github.com/eskerda/pybikes/blob/master/pybikes/data/nextbike.json#L2069

**Comment by eskerda** [comment]
@rytilahti thanks for noticing. Fixed and added a test

**Comment by rytilahti** [comment]
That was quick, thank you very much! :+1:
