### ISSUE TITLE
Add Slovnaftbajk, Bratislava

### ISSUE THREAD

**Issue by andrewshadura** [eskerda/pybikes#334]
Hi,

Bratislava’s got another bike sharing network, https://slovnaftbajk.sk/en/stations

**Comment by andrewshadura** [comment]
See also http://bikes.oobrien.com/bratislava/#zoom=13&lon=17.0922&lat=48.1202

**Comment by eskerda** [comment]
@andrewshadura Does it replace the current white bikes system in Bratislava or is it complementary?

**Comment by andrewshadura** [comment]
It does not, it is a separate system, both will continue to operate.

**Comment by MichalPP** [comment]
@andrewshadura  should we use cyklokoalicia parsing output?

the easiest way would be to use output from cyklokoalicia/OpenSourceBikeShare function in `command.php?action=map:markers`. then, on pybikes only https://github.com/perliedman/leaflet-routing-machine/issues/449 would have to be used again.

**Comment by andrewshadura** [comment]
Ehm, why?

**Comment by MichalPP** [comment]
live data are here: https://routing.epsilon.sk/slovnaftbajk.php

the syntax is the same as OpenSourcebikeshare but with extra column `slotcount`

**Comment by MichalPP** [comment]
and what about green bikes?

**Comment by andrewshadura** [comment]
Oh, great, your data mining techniques are impressive :slightly_smiling_face:
What are the green bikes? I’ve not heard of them (yet).

**Comment by MichalPP** [comment]
https://www.zelenybicykel.sk/ in Prievidza, the ones that reprogrammed OpenSourceBikeShare without forking it..

**Comment by eskerda** [comment]
> live data are here: https://routing.epsilon.sk/slovnaftbajk.php
> 
> the syntax is the same as OpenSourcebikeshare but with extra column `slotcount`

I am happy to add this source, since we already support the Open Source Bike Share syntax, but is it canonical or, if not, do we have permission to use it? We always ask for permission on non-authoritative sources.

**Comment by eskerda** [comment]
> routing.epsilon.sk is my server, so you have permission to use it (it runs routing services like [this](https://www.freemap.sk/?map=15/48.149524/17.110863&layers=A&tool=route-planner&points=48.147906/17.106056,48.159673/17.135024&transport=bikesharing) )
> 
> data is gathered by cyklokoalicia (NGO based in Bratislava focusing on bicycle infrastructure, which also developed OpenSourceBikeShare), stand location (lat/lon) is from openstreetmap

Works for me! Thanks for the permission and for setting up the translation layer!

**Comment by eskerda** [comment]
@MichalPP  I was now checking, https://routing.epsilon.sk/slovnaftbajk.php seems to only have 6 stations, compared to slovnaftbajk.sk which seems to have a lot more. Is that right?

**Comment by MichalPP** [comment]
yes, the stations are not yet fully loaded into OSM, give it a couple of days. the location on slovnaftbajk website is not very accurate (sometimes 100m off), so it's not an automatic import.

**Comment by eskerda** [comment]
Ah ok, now I get the OSM part. Cool integration!
