### ISSUE TITLE
Add PubliBike, Switzerland

### ISSUE THREAD

**Issue by amadeous** [eskerda/pybikes#337]
There's a bike system across Switzerland that could be added to your listing : PubliBike https://www.publibike.ch/en/publibike
This is a complementary system, not replacing any previous system that I am aware of.

**Comment by Manu1400** [comment]
Map: https://www.publibike.ch/en/publibike/stations/

**Comment by Manu1400** [comment]
Wikidata item: https://www.wikidata.org/wiki/Q3555363

**Comment by eUgEntOptIc44** [comment]
I started to implement this in the branch [*eugentoptic44-add-publibike-ch*](https://github.com/eUgEntOptIc44/pybikes/tree/eugentoptic44-add-publibike-ch) of my fork. Please see [publibike.py](https://github.com/eUgEntOptIc44/pybikes/blob/e1893c72cd7a58f09186937df441c4e1bf6df1d0/pybikes/publibike.py#L21) for the current status.
