### ISSUE TITLE
Wrong information for goodbike

### ISSUE THREAD

**Issue by mirh** [eskerda/pybikes#363]
http://api.citybik.es/v2/networks/goodbike and
http://www.goodbikepadova.it/frmLeStazioni.aspx?ID=59
Disagrees quite much.

**Comment by eskerda** [comment]
All bicincitta systems were broken. The issue has been now fixed.

@mirh thanks for reporting!

**Comment by mirh** [comment]
Ehrm.. it broke again.

**Comment by eskerda** [comment]
I think it's ok, at least now

![image](https://user-images.githubusercontent.com/208952/54228879-5a3f0580-44c0-11e9-817f-62addbf6e87d.png)

![image](https://user-images.githubusercontent.com/208952/54228897-61661380-44c0-11e9-9b73-b14e7bc6bbc4.png)
