### ISSUE TITLE
Montreal feed shows only one station

### ISSUE THREAD

**Issue by f8full** [eskerda/pybikes#368]
There seem to be an odd issue with the processing of montreal gbfs data
https://api.citybik.es/v2/networks/bixi-montreal shows only one station.
`{"network":{"company":["Motivate International, Inc.","PBSC Urban Solutions","BIXI Montr\u00e9al"],"gbfs_href":"https://api-core.bixi.com/gbfs/gbfs.json","href":"/v2/networks/bixi-montreal","id":"bixi-montreal","location":{"city":"Montr\u00e9al, QC","country":"CA","latitude":45.508693,"longitude":-73.553928},"name":"Bixi","stations":[{"empty_slots":2,"extra":{"address":null,"last_updated":1552480170,"renting":0,"returning":1,"uid":"325"},"free_bikes":0,"id":"a7afd9e31b77c9217089e1b5e26e4e88","latitude":45.54431114893366,"longitude":-73.54554891586304,"name":"Aylwin / Ontario","timestamp":"2019-03-13T12:55:15.935000Z"}]}}`

The feed url from https://github.com/eskerda/pybikes/blob/cf599d1192a380194f846606b0d47678c88f6d9a/pybikes/data/gbfs.json#L46

and [checking it](https://api-core.bixi.com/gbfs/gbfs.json) seems correct as it gives
`{"last_updated":1552773810,"ttl":10,"data":{"en":{"feeds":[{"name":"station_information","url":"https://api-core.bixi.com/gbfs/en/station_information.json"},{"name":"station_status","url":"https://api-core.bixi.com/gbfs/en/station_status.json"},{"name":"system_information","url":"https://api-core.bixi.com/gbfs/en/system_information.json"},{"name":"system_alerts","url":"https://api-core.bixi.com/gbfs/en/system_alerts.json"}]},"fr":{"feeds":[{"name":"station_information","url":"https://api-core.bixi.com/gbfs/fr/station_information.json"},{"name":"station_status","url":"https://api-core.bixi.com/gbfs/fr/station_status.json"},{"name":"system_information","url":"https://api-core.bixi.com/gbfs/fr/system_information.json"},{"name":"system_alerts","url":"https://api-core.bixi.com/gbfs/fr/system_alerts.json"}]},"es":{"feeds":[{"name":"station_information","url":"https://api-core.bixi.com/gbfs/es/station_information.json"},{"name":"station_status","url":"https://api-core.bixi.com/gbfs/es/station_status.json"},{"name":"system_information","url":"https://api-core.bixi.com/gbfs/es/system_information.json"},{"name":"system_alerts","url":"https://api-core.bixi.com/gbfs/es/system_alerts.json"}]}}}`

which allows to retrieve the [station_information url](https://api-core.bixi.com/gbfs/en/station_information.json)

which shows a full system 

I'm not sure how proceed so just documented it as a start.

**Comment by f8full** [comment]
ah, it seems stations are coming back, probably because they are being physically placed back into the streets. It's different from the other years.
Closing this issue.

**Comment by eskerda** [comment]
@f8full I found the issue. The gbfs parser is ignoring stations that have the `is_installed` flag set to 0. I think we should not ignore them, let me open an issue about that.

Thanks for reporting!

**Comment by f8full** [comment]
Thks a lot ! Doing a huge refactor of findmybikes (MIT licensed) to add new features, as always many many thks for the great project.
