### ISSUE TITLE
GBFS: do not ignore stations with is_installed set to 0

### ISSUE THREAD

**Issue by eskerda** [eskerda/pybikes#369]
The gbfs parser is ignoring stations that have the is_installed flag set to 0. I think we should not ignore them. See: https://github.com/eskerda/pybikes/issues/368

**Comment by f8full** [comment]
Maybe a temp workaround would be to set them as locked ?

**Comment by eskerda** [comment]
The thing with this flag, for other providers, it means the station is a test station or it is a planned station. That's why we were ignoring them 😕

**Comment by eskerda** [comment]
The issue with montreal seems since fixed, and ignoring stations that are not installed is still sensible I think
