### ISSUE TITLE
Issues in Decobike

### ISSUE THREAD

**Issue by eskerda** [eskerda/pybikes#37]
There are multiple issues with current decobike feeds:
* Some stations appear to be on the Gulf of Guinea (0,0) on Long Beach feed
* San Diego stations are all empty ~~and also include Miami Beach stations~~

**Comment by bparmentier** [comment]
> San Diego stations are all empty

http://www.kpbs.org/news/2015/jan/02/san-diego-bike-sharing-program-scheduled-begin-mon/

**Comment by eskerda** [comment]
Fixed by: https://github.com/eskerda/pybikes/pull/60
