### ISSUE TITLE
Use public GBFS feed for Urban Sharing systems

### ISSUE THREAD

**Issue by geirarne** [eskerda/pybikes#373]
The `bysykkel` implementation points to the Urban Sharing graphQL API:

https://github.com/eskerda/pybikes/blob/029d6bc4fa5c3dcdb06ba1d5b34db7b94e687c62/pybikes/bysykkel_graphql.py#L7

This is not an open data api covered by any license, it is not documented, and can/will change without further notice. 
Instead use our documented GBFS feeds:

https://oslobysykkel.no/en/open-data/realtime
https://trondheimbysykkel.no/en/open-data/realtime
https://bergenbysykkel.no/en/open-data/realtime
https://edinburghcyclehire.com/en/open-data/realtime

(best regards, Geir Arne, product manager for software @ Urban Sharing)

**Comment by eskerda** [comment]
@geirarne thanks for filling an issue. Moved the feeds to use gbfs.

Takk!
