### ISSUE TITLE
Port to Python 3

### ISSUE THREAD

**Issue by selurvedu** [eskerda/pybikes#374]
It's time.

> Being the last of the 2.x series, 2.7 will have an extended period of maintenance. Specifically, 2.7 will receive bugfix support until January 1, 2020. After the last release, 2.7 will receive no support.

https://www.python.org/dev/peps/pep-0373/

**Comment by bdmbdsm** [comment]
@selurvedu did you made some estimates about the complexity of port?

**Comment by selurvedu** [comment]
> @selurvedu did you made some estimates about the complexity of port?

No, not yet :)

**Comment by hugovk** [comment]
Please see PR #397 for a start.

**Comment by eskerda** [comment]
Mostly done right?
