### ISSUE TITLE
add .bicyklezadobreskutky, presov, Slovakia

### ISSUE THREAD

**Issue by MichalPP** [eskerda/pybikes#375]
add presov bike sharing using [open source bikeshare](https://github.com/eskerda/pybikes/blob/master/pybikes/open_source_bike_share.py) with [this url](https://app.bicyklezadobreskutky.sk/command.php?action=map:markers) as source data.

**Comment by eskerda** [comment]
Thanks for reporting the issue and fixing it on a PR @MichalPP 🚲
