### ISSUE TITLE
Endpoint for BA Bikes

### ISSUE THREAD

**Issue by RacoFernandez** [eskerda/pybikes#378]
Hi, 

The endpoint https://recursos-data.buenosaires.gob.ar/ckan2/ecobici/estado-ecobici.xml is no longer updated (it belongs to the old public bikes system). You will be available to get the data soon from https://www.buenosaires.gob.ar/desarrollourbano/transporte/apitransporte/api-doc in GBFS format. 

Thanks!

**Comment by eskerda** [comment]
@RacoFernandez cool, thanks for letting us know! It would be nice if you can report back once it's available.

**Comment by RacoFernandez** [comment]
@eskerda Hi, the information of Buenos Aires's new public bike system is available at https://www.buenosaires.gob.ar/desarrollourbano/transporte/apitransporte/api-doc (it's the documentation of the public transportation of Buenos Aires). We are shutting down the XML you are consuming with this (it's the information of the old system), we can drop it once you have changed the data, let us know!

You have to register in the API to consume it. Let us know if you have any doubt (most of the documentation is in Spanish, sorry for that).

Thanks.

**Comment by eskerda** [comment]
@RacoFernandez gracias por la info y por la atención manteniendo el XML durante la migración a GBFS!

Un saludo

**Comment by eskerda** [comment]
@RacoFernandez it seems the gbfs feed is currently returning two test stations in Brazil and Canada. Any info on that?

**Comment by RacoFernandez** [comment]
@eskerda Hi! Thanks for notifying us. I am going to report this to the API Transport team to remove these two test stations.
