### ISSUE TITLE
Proposal to merge Miami Beach + Downtown Miami = DecoBike Miami

### ISSUE THREAD

**Issue by eskerda** [eskerda/pybikes#38]
http://www.decobikesurfside.com/map-location

**Comment by bparmentier** [comment]
FYI, http://www.decobikesurfside.com/playmoves.xml is the same feed as http://www.decobike.com/playmoves.xml, except that by looking at the header, one seems more recent than the other.

**Comment by eskerda** [comment]
Yep, now that I recall that's why it was never added. SurfSide is just a subcollection of Miami.

And the global Miami decobike is just that plus downtown http://citibikemiami.com/station-map

I think we should just merge it into one and only network.

**Comment by eskerda** [comment]
http://citibikemiami.com/miami-beach-locations.xml + http://citibikemiami.com/downtown-miami-locations.xml

**Comment by eskerda** [comment]
No longer relevant: https://github.com/eskerda/pybikes/pull/60
