### ISSUE TITLE
Fix cyclopolis rhodes

### ISSUE THREAD

**Issue by eskerda** [eskerda/pybikes#382]
https://rhodes.cyclopolis.gr/index.php/en/stations

**Comment by eUgEntOptIc44** [comment]
Hi @eskerda 

I just wrote a little script to validate the current status: https://gist.github.com/eUgEntOptIc44/4b4c808a0f1f10835f92b9482d7b2bfe.

Hope this might be helpful.

**Comment by eskerda** [comment]
Fixed by https://github.com/eskerda/pybikes/pull/558
