### ISSUE TITLE
Fix velobike.ru

### ISSUE THREAD

**Issue by eskerda** [eskerda/pybikes#385]
https://velobike.ru/en/parkings/

**Comment by Snarkorel** [comment]
Bike stations data for velobike_ru can be obtained here: https://velobike.ru/ajax/parkings/

Currently parser is broken, it uses old API (http://apivelobike.velobike.ru/ride/parkings), which is not supported now. Message says "You have old version of app installed, it will be deprecated soon. You should update your app"

**Comment by Snarkorel** [comment]
I've fixed this issue and created a pull request #409

**Comment by Altonss** [comment]
The issue seems fixed, so we could close the issue @eskerda?
