### ISSUE TITLE
Add support for socialbicycles.com

### ISSUE THREAD

**Issue by eskerda** [eskerda/pybikes#39]
http://coast.socialbicycles.com/

**Comment by eskerda** [comment]
Just throwing this link here https://app.socialbicycles.com/developer

**Comment by jmfield2** [comment]
I've implemented a SoBi updater for OpenTripPlanner - if it's still needed I can try to port it over.  Do any other networks in pybikes need authentication to read from the upstream API like socialbicycles?  Currently I use OAuth

**Comment by eskerda** [comment]
> I've implemented a SoBi updater for OpenTripPlanner - if it's still needed I can try to port it over. Do any other networks in pybikes need authentication to read from the upstream API like socialbicycles? Currently I use OAuth

No. Only auth so far are API keys that are made available to pybikes through a config file. Can you recommend any oauth python lib?

**Comment by nighthawk** [comment]
FWIW, the bearer tokens for Social Bicycles are very long lived. So you can access it by providing an `Authorization: Bearer $token` header rather than going full OAuth.

**Comment by eskerda** [comment]
Seems some (if not all?) sobi feeds support gbfs http://biketownpdx.socialbicycles.com/opendata/gbfs.json

So together with https://github.com/eskerda/pybikes/issues/140 it might get easier

**Comment by eskerda** [comment]
https://github.com/eskerda/pybikes/pull/195
