### ISSUE TITLE
MVGmeinRad, Mainz, Germany broken

### ISSUE THREAD

**Issue by ulope** [eskerda/pybikes#392]
The MVGmeinRad provider seems to be broken.

Both on citybik.es as well as in apps using the API no useful results are shown.

**Comment by eUgEntOptIc44** [comment]
The openlayers based map at [netz.mainzer-mobilitaet.de/#poiLayers=nextbike](https://netz.mainzer-mobilitaet.de/#poiLayers=nextbike) displays their bikes. The URL suggest that they use nextbike.

**Comment by eUgEntOptIc44** [comment]
The internal `domain` for Mainz at nextbike is `mz` see the following url for all bikes in Mainz:

`https://api[.]NEXTBIKE[.]net/maps/nextbike-live[.]json?domains=mz`

(I had to add some brackets to prevent me showing up in their search alerts)

**Comment by eUgEntOptIc44** [comment]
@ulope I'll open a PR to update the nextbike data very soon.

**Comment by ulope** [comment]
Interesting. They are definitely not nextbike hardware though.
