### ISSUE TITLE
API Down

### ISSUE THREAD

**Issue by Catherinesjkim** [eskerda/pybikes#403]
It looks like your API is down. Can you please check? https://worldwide-bicycle-stations.now.sh/

Thanks, 
Catherine

**Comment by eskerda** [comment]
<img width="836" alt="image" src="https://user-images.githubusercontent.com/208952/74970227-4a44db00-541e-11ea-902c-2e7f0ffea16b.png">


The API works fine. Also, this repo is for pybikes, not the citybikes api.

**Comment by Catherinesjkim** [comment]
Thanks for pointing that out. Two questions.

1. Do you know why when I deploy this web app to Zeit, your API data is not pulling in? Other open source API with http work fine on Zeit. 

2. Any plans to update it to https which is more secure? Thanks!

**Comment by eskerda** [comment]
The API does support https (https://api.citybik.es). It just does not redirect http to https to avoid breaking old clients relying in http and not supporting https or redirects.

This React Redux app just has a typo. Substitute all http calls to https, or use `://` so it uses either http or https.
