### ISSUE TITLE
Your HTTP API is Not Pulling in Data when the App is Deployed via Zeit Due to Mixed Content

### ISSUE THREAD

**Issue by Catherinesjkim** [eskerda/pybikes#404]
1. Do you know why when I deploy this React Redux app to Zeit, your API data is not pulling in? Other open source API with http work fine on Zeit. https://react-redux-app-gold.now.sh/

2. Any plans to update it to https which is more secure? Thanks!
https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content

**Comment by albertvaka** [comment]
This has been answered in https://github.com/eskerda/pybikes/issues/403
