### ISSUE TITLE
bicimad JSON error

### ISSUE THREAD

**Issue by xavidelclos** [eskerda/pybikes#407]
Hi Lluís,

I was trying to download the data from BiciMad and I got the following error. Do you know what the problem might be?

Best,
Xavi

---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-27-da415ba3dfb9> in <module>
----> 1 bicimad.update()

C:\ProgramData\Anaconda3\lib\site-packages\pybikes\bicimad.py in update(self, scraper)
     45                                    data=json.dumps(payload))
     46         # Double JSON is always better than single JSON :)
---> 47         data = json.loads(json.loads(response)['data'])
     48         self.stations = [BicimadStation(s) for s in data['stations']]
     49 

C:\ProgramData\Anaconda3\lib\json\__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    346             parse_int is None and parse_float is None and
    347             parse_constant is None and object_pairs_hook is None and not kw):
--> 348         return _default_decoder.decode(s)
    349     if cls is None:
    350         cls = JSONDecoder

C:\ProgramData\Anaconda3\lib\json\decoder.py in decode(self, s, _w)
    335 
    336         """
--> 337         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338         end = _w(s, end).end()
    339         if end != len(s):

C:\ProgramData\Anaconda3\lib\json\decoder.py in raw_decode(self, s, idx)
    353             obj, end = self.scan_once(s, idx)
    354         except StopIteration as err:
--> 355             raise JSONDecodeError("Expecting value", s, err.value) from None
    356         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by eskerda** [comment]
You need a valid API key (provided by them or their app) for accessing madrid's bike share system data
