### ISSUE TITLE
New potential data source: Tucson, AZ TuGo bike share

### ISSUE THREAD

**Issue by ianmcorvidae** [eskerda/pybikes#421]
https://tugobikeshare.com/system-map/

I'm not sure if there's an API or anything, but I noticed it wasn't on CityBikes and thought the project might appreciate the heads-up!

**Comment by Altonss** [comment]
A Gbfs feed is available for Tucson here: https://tucson-us.publicbikesystem.net/ube/gbfs/v1/
We just need to add it :)

**Comment by eUgEntOptIc44** [comment]
> A Gbfs feed is available for Tucson here: https://tucson-us.publicbikesystem.net/ube/gbfs/v1/ We just need to add it :)

@Altonss the gbfs feed does **not** seem to exist anymore. The url unfortunately returns a error message.

**Comment by Altonss** [comment]
> > A Gbfs feed is available for Tucson here: https://tucson-us.publicbikesystem.net/ube/gbfs/v1/ We just need to add it :)
> 
> @Altonss the gbfs feed does **not** seem to exist anymore. The url unfortunately returns a error message.

Somehow it works for me in a browser :thinking:

**Comment by eUgEntOptIc44** [comment]
> Somehow it works for me in a browser 🤔

Happy to confirm this. Error is gone. 👍
