### ISSUE TITLE
V'Lille (Lille (FR)) is not updating fast enough

### ISSUE THREAD

**Issue by Altonss** [eskerda/pybikes#449]
Would it be possible to query more frequently the V'Lille api? Because as of now the pybikes api is delayed by several minutes.
ping @eskerda ;)

**Comment by martgnz** [comment]
Have you tried running pybikes locally to see if updates come faster? That's what I would do if I needed a very high update frequency.

**Comment by eskerda** [comment]
Closing this issue since it is not related to pybikes, but the Citybikes API. As Martin said, if you want higher update freqs just run pybikes yourself.
