### ISSUE TITLE
Samba provider doesn't work anymore for many cities!

### ISSUE THREAD

**Issue by Altonss** [eskerda/pybikes#458]
Networks affected:
- [ ] "bikebh",
- [ ] "bikepetrolina",
- [x] "bikebrasilia",
- [ ] "debikegoiania",
- [ ] "bicicletar",
- [ ] "cajubike",
- [ ] "bikebelem",
- [x] "mibicitubici",

The only one working is : "bikesantos".

**Comment by martgnz** [comment]
- bikebh recently switched to tembici which usually has GBFS feeds available. I can't find it for this one, though: https://www.tembici.com.br/en/belo-horizonte/
- bike petrolina seems to have been shut down? according to https://bikesharemap.com/petrolina/#/15/-40.4908/-9.3954/
- debikegoiania seems to have moved to http://gyndebike.com.br/mapaestacao.aspx but it is returning 0 stations. the payment site is down and the app has been removed. i don't think it is operating.
- bicicletar seems to be working now!
- i don't think cajubike is operative, the site is down and i found this article: https://www.f5news.com.br/cotidiano/servico-do-caju-bike-e-desativado-em-aracaju_46514/
- i don't think bikebelem is operative either, this thesis says it was shut down in 2020: https://bdm.ufpa.br:8443/jspui/bitstream/prefix/3636/1/TCC_MicromobilidadeBelemAnalise.pdf
