### ISSUE TITLE
Velib (Smoovengo) is broken

### ISSUE THREAD

**Issue by Phyks** [eskerda/pybikes#462]
Hi,

Velib is currently gathered through a scraping process, which have been behind Cloudflare for a couple of days. As a result, pybikes is no longer working on this system, except for very small datasets.

Velib does have a GBFS 1.0 API endpoint: https://www.velib-metropole.fr/donnees-open-data-gbfs-du-service-velib-metropole.

It can be accessed without any license key and under an Open Data license.

Pybikes should probably move to this API?

https://velib-metropole-opendata.smoove.pro/opendata/Velib_Metropole/station_information.json provides the full list of stations.

https://velib-metropole-opendata.smoove.pro/opendata/Velib_Metropole/station_status.json returns the full stations status.

**Comment by Altonss** [comment]
Thanks a lot @Phyks for this info!
I will ping @eskerda which is the only one to have write access to this repo! Hopefully this can be fixed soon!

**Comment by Altonss** [comment]
> Hi,
> 
> Velib is currently gathered through a scraping process, which have been behind Cloudflare for a couple of days. As a result, pybikes is no longer working on this system, except for very small datasets.
> 
> Velib does have a GBFS 1.0 API endpoint: https://www.velib-metropole.fr/donnees-open-data-gbfs-du-service-velib-metropole.
> 
> It can be accessed without any license key and under an Open Data license.
> 
> Pybikes should probably move to this API?
> 
> https://velib-metropole-opendata.smoove.pro/opendata/Velib_Metropole/station_information.json provides the full list of stations.
> 
> https://velib-metropole-opendata.smoove.pro/opendata/Velib_Metropole/station_status.json returns the full stations status.

Is the GBFS feed as up to date as the current end point was? (I mean the data latency)

**Comment by Phyks** [comment]
Both endpoints indicates last updated / last reported values.

In https://www.velib-metropole.fr/donnees-open-data-gbfs-du-service-velib-metropole, they mention they should be minutely refreshed.

**Comment by eskerda** [comment]
@Phyks @Altonss thanks for the report!
