### ISSUE TITLE
(Wien) CityBike is replaced by NextBike/WienMobil Rad

### ISSUE THREAD

**Issue by opk12** [eskerda/pybikes#466]
Hello. Since April 1, 2022, WienMobil Rad will be the new bike sharing operator. CityBike is being dismantled. [Source](https://citybikewien.at/de/news/864-citybike-wien-betriebseinstellung-mit-31-3-2022)

WienMobil [says](https://www.wienerlinien.at/wienmobil/rad) that NextBike will provide the service.

**Comment by Altonss** [comment]
Thanks a lot for the info, as far as I know we already have a implementation for the NextBike provider, so would just need to have the corresponding URL :)

**Comment by bc-mihai** [comment]
According to the current status of the site (https://www.nextbike.at/de/wien/) it's the "nextbike_wr" domain, see #467

**Comment by eskerda** [comment]
Fixed with https://github.com/eskerda/pybikes/pull/467

thanks!
