### ISSUE TITLE
add Kiel

### ISSUE THREAD

**Issue by pyth2-0** [eskerda/pybikes#473]
Hey,

is there a possibility to add Kiel? 
The provider is "Nextbike" 
The Region ID is 613
The Api is here https://api.nextbike.net/maps/nextbike-live.json?city=613

cheers

**Comment by Altonss** [comment]
I have opened a PR to add Kiel. So now we just need to wait for @eskerda to approve the PR and to merge it :)

**Comment by pyth2-0** [comment]
nice thank you.
