### ISSUE TITLE
Empty networks (no station in stations list)

### ISSUE THREAD

**Issue by Altonss** [eskerda/pybikes#475]
Empty networks : 
- [x] 'cycle-hire-slough'
- [x] 'cyclopolis-nafplio'
- [x] 'cyclopolis-moschatotavros'
- [x] 'cyclopolis-rhodes'
- [x] 'cyclopolis-florina'
- [x] 'cyclopolis-limnos'
- [x] 'punpunbikeshare'
- [x] 'wowcycle-reykjavik'
- [x] 'easybike-nicosia'
- [x] 'bici-ferrol-terra'
- [x] 'curtin-bike-share'
- [x] 'velogo'
- [x] 'juice-bike-share'
- [x] 'mountain-rides-bike-share'
- [x] 'nice-ride'
- [x] 'bicialtea'
- [x] 'bicidorm'
- [x] 'saforbici'
- [x] 'gbici'
- [x] 'muybici'
- [x] 'ponfemobi'
- [x] 'vaibike'
- [x] 'rivibike'
- [x] 'dukebike'
- [x] 'baksi-istanbul'
- [x] 'telofun'
- [x] 'slovnaft-bajk'
- [x] 'mvgmeinrad'
- [x] 'encicla'
- [x] 'bikebh'
- [x] 'cajubike'
- [x] 'mibicitubici'
- [x] 'decobike-san-diego'
- [x] 'battlecreek'
- [x] 'greenville'
- [x] 'nashville'
- [x] 'catbike'
- [x] 'nextbike-ivano-frankivsk'

**Comment by eskerda** [comment]
See full report of networks returning no stations at https://github.com/eskerda/pybikes/actions/runs/2789411405#summary-7651901142

**Comment by Altonss** [comment]
> See full report of networks returning no stations at https://github.com/eskerda/pybikes/actions/runs/2789411405#summary-7651901142 (ignore feeds that have authentication like Cyclocity as these are not working on the CI yet)

That's great, thank you!

**Comment by Altonss** [comment]
Ecobici ba seems to fail on CI, but somehow the feed is working (at least sometimes).
If needed we could change the endpoint to #496

**Comment by eskerda** [comment]
ecobici needs auth, so it is failing on CI

**Comment by Altonss** [comment]
but this one is only a gbfs feed I think...

**Comment by eskerda** [comment]
https://github.com/eskerda/pybikes/blob/master/pybikes/ecobici_ba.py

**Comment by eUgEntOptIc44** [comment]
@Altonss 

updates on your list:

* `mvgmeinrad` --> see #514 
* the following `cyclopolis` sites are broken (and no possible fix available so far) --> also see #382 [^1]
    * `cyclopolis-maroussi`
    * `cyclopolis-aigialeia`
    * `cyclopolis-marathon`
    * `cyclopolis-neasmyrni`
    * `cyclopolis-arxaiaolympia`
    * `cyclopolis-kiato`


[^1]: also see my script at https://gist.github.com/eUgEntOptIc44/4b4c808a0f1f10835f92b9482d7b2bfe for further insights into my method to validate the raw data

**Comment by eskerda** [comment]
I have marked all tasks done, by either fixing them, or creating new issues.
