### ISSUE TITLE
Add Montpellier 🇫🇷 

### ISSUE THREAD

**Issue by Manu1400** [eskerda/pybikes#481]
GBFS 🥳  feed_url: https://montpellier-fr-smoove.klervi.net/gbfs/gbfs.json

documentation in french: https://transport.data.gouv.fr/datasets/disponibilite-en-temps-reel-des-velos-en-libre-service-velomagg-de-montpellier/

**Comment by Altonss** [comment]
Great, thanks for the info!
You could do a very simple PR, similar to what I have done with Monaco here https://github.com/eskerda/pybikes/pull/446
But if you are not a developer/don't know how to do/don't feel confortable that's not an issue, I will do it as soon as I have time ;)

**Comment by Altonss** [comment]
I have finally made the PR, it just need to get merged now ;)
