### ISSUE TITLE
Network "Tel-O-Fun" seems to be broken

### ISSUE THREAD

**Issue by francoisfds** [eskerda/pybikes#490]
Hello. Congratulations for this project :)

It seems that the network "Tel-O-Fun" (city of Tel Aviv, Israel) is currently broken because the "feed_url" is dead. The operator is still alive, though.

An accurate feed is available on this link : https://gisn.tel-aviv.gov.il/arcgis/rest/services/IView2/MapServer/835/query?where=1%3D1&outFields=*&f=json (documentation here https://opendata.tel-aviv.gov.il/en/pages/item.aspx?ids=6&tab=map#1a)

Data corresponds to the map displayed on the official website : https://www.tel-o-fun.co.il. Based on it I believe the conversion for the API is something like this :
```
free_bikes <- free_bikes + free_bikesE
empty_slots <- free_amudim + free_amudimE
extra.ebikes <- free_bikesE
```

Regards.

**Comment by Altonss** [comment]
Thanks a lot for all these informations! I will try to open a PR with the fixes as soon as I have the time for it ;)

**Comment by eskerda** [comment]
https://www.tel-o-fun.co.il/api/privatearea/v1/map
