### ISSUE TITLE
Add Oldenburg OLi Nextbike

### ISSUE THREAD

**Issue by BuZZ-dEE** [eskerda/pybikes#491]
Please add Oldenburg Niedersachsen Germany [OLi Nextbike](https://www.oli-bike.de/en/).

![IMG_20220730_141015](https://user-images.githubusercontent.com/125954/181913667-d7c3ba7a-5389-470b-9d6d-17a1b1e7e110.jpg)

https://www.oli-bike.de/en/

**Comment by Altonss** [comment]
I added the network in the pull request #492 ;) @BuZZ-dEE
