### ISSUE TITLE
"Bycyklen" in Copenhagen seems to be broken

### ISSUE THREAD

**Issue by futuretap** [eskerda/pybikes#499]
The last timestamp is from 04/2020.

**Comment by eskerda** [comment]
All three feeds on `gobike` are broken at the moment:

* Utrecht does not return anything anymore http://nu-connectutrecht.nl
* Copenhagen website has changed and does not display stations anymore https://bycyklen.dk We need to check the app, or look for an open data feed? Very strange that denmark does not offer this
* Stavanger http://bysykkelen.no has also changed provider.

**Comment by eskerda** [comment]
That's good info, thanks! I guess we can nuke the current implementation and start working on these feeds separately

**Comment by eUgEntOptIc44** [comment]
Hi @eskerda 

Thanks for your feedback.

I also looked into the current state of bike sharing in **Utrecht**. They offer some hints at https://welcome.utrechtregion.com/en/life/getting-around/biking. Adding *OV fiets* (#309) seems to be the best option for now.

Acoording to a [reddit](https://www.reddit.com/r/Utrecht/comments/t58vlj/bike_rental_for_a_few_hours/) user *Tier* [^1] is apparently also in the bike sharing business in Utrecht.

On a side note I'd like to add that *Tier* acquired *Nextbike* in November of 2021. [(German source)](https://app.handelsblatt.com/unternehmen/handel-konsumgueter/fahrradverleiher-tier-uebernimmt-nextbike-und-wird-so-zum-partner-vieler-kommunen/27801562.html)
So they might adapt or use the *Nextbike* software stack for their bikes at some point.

[^1]: also see https://api-documentation.tier-services.io for their API docs

**Comment by eskerda** [comment]
Hello @eUgEntOptIc44 , thanks for the patch. So the reason for not using the regular GBFS parser is that the systems are not logically grouped then?

I see there are many instances with only one to three stations, is that correct?
