### ISSUE TITLE
If a PBSC city has e-bikes, please indicate the number of e-bikes in the extra property

### ISSUE THREAD

**Issue by unforgettableid** [eskerda/pybikes#502]
# Background information

PBSC is a company which sells bike-share products and services worldwide, including a technology platform.  If a city uses PBSC's technology platform, the city will include `publicbikesystem.net` somewhere in its feed URL.

Some PBSC cities have e-bikes.  (Example:  Bike Share Toronto, https://tor.publicbikesystem.net/ube/gbfs/v1/gbfs.json.)

Other PBSC cities don't have any e-bikes.  (Example:  SBU Wolf Ride Bike Share, https://stonybrook.publicbikesystem.net/ube/gbfs/v1/gbfs.json.)

To tell how many ebikes a PBSC station has, you load the GBFS v1 [station_status](https://tor.publicbikesystem.net/ube/gbfs/v1/en/station_status) feed file.  Then, you look inside `num_bikes_available_types`.

Example:

> {"station_id":"7645","num_bikes_available":10,"num_bikes_available_types":{"mechanical":8,"ebike":2},"num_bikes_disabled":4,"num_docks_available":1,"num_docks_disabled":0,"last_reported":1661705184,"is_charging_station":false,"status":"IN_SERVICE","is_installed":1,"is_renting":1,"is_returning":1,"traffic":null}

The above station has 8 mechanical bikes and 2 ebikes.

(You can also determine e-bike counts from PBSC's newer GBFS v2 endpoints, such as [this one](https://tor.publicbikesystem.net/customer/gbfs/v2/en/station_status), but it requires slightly more work.  "Boost" and "EFit" bikes are e-bikes; "Iconic" bikes are mechanical.)

# My request

If a PBSC station has e-bikes, it would be good if pybikes could please update the extra property to indicate the number of e-bikes.

# Conclusion

Thank you for all the work you've put into pybikes!

**Comment by jeffmurchison** [comment]
This would be a great addition!

**Comment by eskerda** [comment]
This commit added support for ebikes on gbfs feeds https://github.com/eskerda/pybikes/pull/542
