### ISSUE TITLE
Missing: Laval (France)

### ISSUE THREAD

**Issue by Manu1400** [eskerda/pybikes#520]
## get live data
```sh
curl 'https://portail.cykleo.fr/pu/stations/availability?organization_id=6' \
  -H 'referer: https://portail.cykleo.fr/velitul/carte_stations'
```

## source
Map : https://portail.cykleo.fr/velitul/carte_stations

## documentation
no documentation from transport.data.gouv.fr ([source](https://transport.data.gouv.fr/datasets/commune/53130)) - 20 december 2022

**Comment by Altonss** [comment]
I know a few cities we could scrape from Cykleo, but unfortunately we would need to write a parser for this...

**Comment by eUgEntOptIc44** [comment]
Hi @Altonss, @Manu1400,

I just finished the implementation of the parser for [*Cykleo*](https://cykleo.fr/). Please see https://github.com/eUgEntOptIc44/pybikes/commit/a1911fc5dcd9d31ad4b8d05389c410670c42dba3 for the source code. As of writing the *data* file contains the following *instances*:

* `cykleo-divia-velodi-dijon` -> 'DiviaVélodi' in 'Dijon (FR)'
* `cykleo-twistovelo-caen` -> 'Twisto vélo' in 'Caen (FR)'
* `cykleo-idecycle-pau` -> 'IDEcycle' in 'Pau (FR)'
* `cykleo-star-rennes` -> 'STAR' in 'Rennes (FR)'
* `cykleo-veloplus-velotao-orleans` -> 'Vélo+/VéloTAO' in 'Orléans (FR)'
* `cykleo-velitul-laval` -> 'Vélitul' in 'Laval (FR)'
* `cykleo-tbm-bordeaux` -> 'TBM_V3' in 'Bordeaux (FR)'
* `cykleo-vlille-lille` -> 'V'lille' in 'Lille (FR)'

If you're aware of more please let me know. 

I also wrote a little Python script to validate the data: https://gist.github.com/eUgEntOptIc44/5eaafcd2d2506a61a39a9a6a99978ec1.

*Off topic* The pages 164-166 of [this French **PDF** document](https://www.entreprises.gouv.fr/files/files/en-pratique/etudes-et-statistiques/dossiers-de-la-DGE/impact-economique-et-potentiel-developpement-velo-en-france.pdf) might be also interesting to learn about further providers.

**Comment by eUgEntOptIc44** [comment]
I forgot to mention that this also concerns the code for *Keolis*. Please see my comment on the PR for further details: https://github.com/eskerda/pybikes/pull/531#issuecomment-1364612752

**Comment by AntoineAugusti** [comment]
👋 we (@ transport.data.gouv.fr) will try to get in touch with Cykleo / Keolis to open up all these feeds in GBFS in 2023.

**Comment by eUgEntOptIc44** [comment]
@AntoineAugusti great news! Is there any public timeline/roadmap available so far?

I already found the list of recently added APIs at https://transport.data.gouv.fr/datasets?order_by=most_recent&type=bike-scooter-sharing. A few of the providers named [above](https://github.com/eskerda/pybikes/issues/520#issuecomment-1364610047) (e.g. *STAR* or *V'lille*) are present but others not.

**Comment by eUgEntOptIc44** [comment]
Hi @AntoineAugusti,
haven't heard from you in a while. Hope your doing good. Is there any news regarding the integrations?
I'd be very grateful for a short update on this promising project.

**Comment by eskerda** [comment]
Added in https://github.com/eskerda/pybikes/pull/580
