### ISSUE TITLE
BIKETOWN (Portland, OR) down

### ISSUE THREAD

**Issue by Manu1400** [eskerda/pybikes#521]
## actual code
https://github.com/eskerda/pybikes/blob/97414d1c9f3ebef6cf96e8637b15a77820d32612/pybikes/data/gbfs.json#L122-L135

## issue
the feed http://biketownpdx.socialbicycles.com/opendata/gbfs.json is broken:
> DNS_PROBE_FINISHED_NXDOMAIN

## proposal
use https://gbfs.biketownpdx.com/gbfs/gbfs.json

### question
- [ ] is it the same feed ?

**Comment by Altonss** [comment]
For me it seems good, the provider of the network has just changed maybe, and is now Lyft. Do you want to do the PR integrating those changes?
