### ISSUE TITLE
Marseille, FR, changed provider, old network is offline, new network started operation

### ISSUE THREAD

**Issue by tuxayo** [eskerda/pybikes#530]
Since two months, part of the old network was converted to the system of the new provider. And a few days ago, the remaining half the of stations of the old network was shutdown. And the new bikes where put the transitioned & new stations.

Page with the map of stations with availability: https://levelo.ampmetropole.fr/sharing#stationsMap
URL to list the stations used by the map: https://levelo.ampmetropole.fr/api/stations

The name of the network is the same, although stylized "levélo"

**Comment by Altonss** [comment]
Work to fix this issue is already being done in this PR I think https://github.com/eskerda/pybikes/pull/515 ;)

**Comment by tuxayo** [comment]
Sorry, I only looked at the issues, not the patch submissions.

**Comment by Altonss** [comment]
@eskerda  thanks for having merged the patch, but just noticed the position of stations is wrong (maybe inverted latitude and longitude?)...

**Comment by eskerda** [comment]
Thanks @Altonss , fixed in https://github.com/eskerda/pybikes/commit/8f6f02562dd3ed2941f2730f6ca9a40d86b3a3ad
