### ISSUE TITLE
"bizi" feed URL changed

### ISSUE THREAD

**Issue by futuretap** [eskerda/pybikes#545]
`https://www.bizizaragoza.com/availability_map/getJsonObject` no longer works.

New URLs:
https://cc-smartbike-opendata.s3.eu-west-1.amazonaws.com/zaragoza/station_list.json
https://cc-smartbike-opendata.s3.eu-west-1.amazonaws.com/zaragoza/station_status_list.json

**Comment by Altonss** [comment]
> New URLs: https://cc-smartbike-opendata.s3.eu-west-1.amazonaws.com/zaragoza/station_list.json https://cc-smartbike-opendata.s3.eu-west-1.amazonaws.com/zaragoza/station_status_list.json

Isn't there a standard GBFS feed available? Because as such it seems we would need to recode a parser (it wouldn't be too much work, but still...).

**Comment by futuretap** [comment]
> Isn't there a standard GBFS feed available? 

Not that I'm aware of.

**Comment by eskerda** [comment]
Fixed https://github.com/eskerda/pybikes/pull/549

**Comment by eskerda** [comment]
For reference, there are the following open data feeds available https://www.zaragoza.es/sede/portal/datos-abiertos/servicio/catalogo/70 but since we have some other ClearChannel systems that might migrate to this new implementation too, I decided to go with the website feeds.

**Comment by futuretap** [comment]
Thank you very much!
