### ISSUE TITLE
"decobike-miami-beach" feed broken

### ISSUE THREAD

**Issue by futuretap** [eskerda/pybikes#546]
The [XML feed](http://www.citibikemiami.com/downtown-miami-locations.xml) yields a 404, the [alternative feed](http://citibikemiami.com/downtown-miami-locations2.xml) is empty.

The [station map](https://www.citibikemiami.com/#stationmap) is constructed from JS embedded into the [HTML page](https://snazzymaps.com/embed/473935) but doesn't include live station data.

**Comment by Altonss** [comment]
Decobike in san diego is broken too!

**Comment by futuretap** [comment]
While the Miami system is still in operation, San Diego seems to be unavailable. The app (Discover bike) doesn't display any bikes.

**Comment by Altonss** [comment]
> San Diego seems to be unavailable. The app (Discover bike) doesn't display any bikes.

I just sent a PR to remove this system, thanks for the information :)

**Comment by eskerda** [comment]
Miami decobike, now called Citi Bike Miami and powered by Lyft. So far have not found any reliable open information feed.
