### ISSUE TITLE
[smartbike] malmobybike feed is stale

### ISSUE THREAD

**Issue by OTHMANE-AKHSAS** [eskerda/pybikes#576]
[malmobybike](https://api.citybik.es/v2/networks/malmobybike) feed seems to be stale (last updated on 4th of July). I think the URL we get data from is outdated. I found some new URLS to use in their website :

- stations list: https://cc-smartbike-opendata.s3.eu-west-1.amazonaws.com/malmo/station_list.json
- station status: https://cc-smartbike-opendata.s3.eu-west-1.amazonaws.com/malmo/station_status_list.json

Can someone look into this 🙏 
Thank you

**Comment by eskerda** [comment]
Fixed, thanks for reporting!
