### ISSUE TITLE
Fix BiciFerrolterra

### ISSUE THREAD

**Issue by eskerda** [eskerda/pybikes#594]
Feed is broken. Their website has no availability info, and there's no app 👏 

https://biciferrolterra.com/

**Comment by Gabriel44200** [comment]
For what it's worth, this is the website where user data is managed. It is based on the old website of the service from when it was managed by nextgal

http://xestion.biciferrolterra.com/Default.aspx

**Comment by eskerda** [comment]
I will try to contact 2ksystems and see if they are interested in opening their data feed

**Comment by Gabriel44200** [comment]
It seems that in citybik.es doesn't work, I will try to test it on a python code but I don't know why the library don't imports well

**Comment by eskerda** [comment]
Fixed an encoding issue that was causing the server to not parse it https://github.com/eskerda/pybikes/commit/01ce2ec70cc5d2e9b3c0899962ac13cec3b02f0e

Anyway, the feed is not moving, it's dead. @Gabriel44200 if you are interested in this feed, try contacting them.

**Comment by Gabriel44200** [comment]
One day when I go to the city I check whether the data matches or not because the service has very low usage, awaiting renewal. The support service does not usually answer, when I know more I will comment

**Comment by Gabriel44200** [comment]
After checking the stations in person it is confirmed that the data matches and is updated, only the usage is so low that it is barely noticeable
