### ISSUE TITLE
Check failed samba systems

### ISSUE THREAD

**Issue by eskerda** [eskerda/pybikes#595]
```
FAILED tests/test_instances.py::TestSamba::test_update[samba.Samba::bikebh] - assert 0 > 0
FAILED tests/test_instances.py::TestSamba::test_update[samba.Samba::bikepetrolina] - assert 0 > 0
FAILED tests/test_instances.py::TestSambaNew::test_update[samba.SambaNew::debikegoiania] - IndexError: list index out of range
FAILED tests/test_instances.py::TestSambaNew::test_update[samba.SambaNew::cajubike] - IndexError: list index out of range
FAILED tests/test_instances.py::TestSambaNew::test_update[samba.SambaNew::bikebelem] - requests.exceptions.SSLError: HTTPSConnectionPool(host='bikebelem.tembici.com.br', port=443): Max retries exceeded with url: /mapaestacao.aspx (Caused by SSLE...
```

**Comment by martgnz** [comment]
- Belo Horizonte is a tembici system but the data doesn't seem to be available in the usual Tembici GBFS endpoints: https://www.tembici.com.br/es/belo-horizonte/
- Petrolina system seems closed? https://www.alingua.com.br/cade-as-bicicletas-publicas-de-petrolina/
- Goiânia's has a new url but the map is empty and the data is not available: http://gyndebike.com.br/mapaestacao.aspx
- Commenters here say cajubike doesn't exist anymore: https://www.viajenaviagem.com/caju-bike-aracaju/
- Bike Belém has shut down: https://parawebnews.com/bike-belem-encerra-suas-atividades/

**Comment by martgnz** [comment]
Related to https://github.com/eskerda/pybikes/issues/458.
