### ISSUE TITLE
Check easybike dead systems

### ISSUE THREAD

**Issue by eskerda** [eskerda/pybikes#599]
There are some dead systems on the easybike implementation. Check if these still exist, or even if it makes sense to have them

```
FAILED tests/test_instances.py::TestEasyBike::test_update[easybike.EasyBike::easybike-kavala] - TypeError: 'NoneType' object is not iterable
FAILED tests/test_instances.py::TestEasyBike::test_update[easybike.EasyBike::easybike-nicosia] - TypeError: 'NoneType' object is not iterable
FAILED tests/test_instances.py::TestEasyBike::test_update[easybike.EasyBike::thessbike] - json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by martgnz** [comment]
- I can't find anything about Kavala. Looking on street view this station seems... abandoned? It's not much to go on, though https://www.google.com/maps/@40.9361921,24.4050854,3a,89.6y,199.52h,77.67t/data=!3m6!1e1!3m4!1sKeTrWiudRZeMMpSaswF9Yw!2e0!7i16384!8i8192?entry=ttu
- Nicosia has a nextbike system. Maybe they moved?
- I found another endpoint for Thessbike: https://github.com/eskerda/pybikes/pull/658
