### ISSUE TITLE
Are station times coming back as CEST and not UTC?

### ISSUE THREAD

**Issue by nixta** [eskerda/pybikes#6]
Looking at the results from api.citybik.es (let's take [CitibikeNYC](http://api.citybik.es/citibikenyc.json) as an example) the station times seem to be coming back `CEST` and not `UTC`.

For example, it is now `14:06 EDT` but the above API call just returned `2013-07-04T20:05:56.903447`.

I can work around this, but am worried that come October 27th, will they switch to CET from CEST?

Or am I missing something?

**Comment by Apol0x** [comment]
Hi! anyone knows how to add one hour o put in my local timezone to the response timestamp to show correct hour for my country (Spain)?
