### ISSUE TITLE
The company field sometimes is an array of string and others is a string in the same request

### ISSUE THREAD

**Issue by DrAP10** [eskerda/pybikes#644]
this two network object are from the same response

{"company":["Comunicare S.r.l."],"href":"/v2/networks/bicincitta-parco-dei-colli-di-bergamo","id":"bicincitta-parco-dei-colli-di-bergamo","location":{"city":"Parco dei Colli di Bergamo","country":"IT","latitude":45.72295637032245,"longitude":9.649230073016383},"name":"Bicincitt\u00e0","source":"https://www.bicincitta.com/frmLeStazioni.aspx?ID=203"}

{"company":"Empresa Municipal de Transportes de Madrid, S.A.","href":"/v2/networks/bicimad","id":"bicimad","location":{"city":"Madrid","country":"ES","latitude":40.4168,"longitude":-3.7038},"name":"BiciMAD","source":"https://mobilitylabs.emtmadrid.es/"}

you can check that in the first one the company field is an array of strings and in the second one the company is a string

**Comment by eskerda** [comment]
Seems like a good first contribution to make! https://github.com/eskerda/pybikes/blob/4816881972c183046f61edf70234eb3845c6176d/pybikes/bicimad.py#L25

**Comment by eskerda** [comment]
Fixced by https://github.com/eskerda/pybikes/pull/646 and https://github.com/eskerda/pybikes/pull/645
