### ISSUE TITLE
Vélomagg, Montpellier : data outdated

### ISSUE THREAD

**Issue by Altonss** [eskerda/pybikes#756]
The last update is from 2024-01-02

**Comment by eskerda** [comment]
gbfs feed seems to not resolve anymore.

I found this url https://cartographie.tam-voyages.com/gtfs/get-resource/velostations

**Comment by eskerda** [comment]
There's also this one https://montpellier-fr.fifteen.site/gbfs/gbfs.json

**Comment by eskerda** [comment]
Yes! Etalab is a life saver in France.
