### ISSUE TITLE
Listing all bikeshare systems

### ISSUE THREAD

**Issue by s2t2** [eskerda/pybikes#80]
Is there a `pybikes` method that makes the api call to list all networks (http://api.citybik.es/networks.json)?

**Comment by eskerda** [comment]
Not by itself. The API is using an storage, so a data model is in place on the API: https://github.com/eskerda/citybikes-api/blob/master/api/models.py

However, it's easy reproducible using pybikes:


```python
import pybikes

for cname, network in pybikes.get_instances():
    print network['tag']
    print network['meta']
    ...
```

BTW, do you know there's a richer endpoint, right? http://api.citybik.es/v2/networks

**Comment by s2t2** [comment]
I did see v2 and the networks endpoint there - its great.  I was wondering if it had been incorporated into the pybikes library.  Ill check out `get_instances(), thanks. FYI - this weekend i wrote a Ruby wrapper for the v2 api... https://github.com/data-creative/citybikes-api-ruby :smile:
