### ISSUE TITLE
Add Mvgmeinrad Mainz, Germany

### ISSUE THREAD

**Issue by BenSto** [eskerda/pybikes#83]
Hi @eskerda,

first of all, thanks for your work, this repository is really impressive and awesome :+1:  !!! There is a provider in Mainz, which also does station based bikesharing and is currently not in your system. Im not really used to work with Python (Im more into Ruby). But I have added a Script to Pybikes and it works so far, as I can assess roughly. I would like to create a PR if thats Ok? 
Best Regards

http://www.mvg-mainz.de/mainzigartig-mobil/mit-mvgmeinrad/stationen.html

**Comment by eskerda** [comment]
Sure, go ahead! 

:bike:  :bike:  :bike:  :bike:  :bike:  :bike:  :bike:  :bike:  :bike:

**Comment by BenSto** [comment]
Hmm I created a new branch from master and wanted to push into it, but got 
`The requested URL returned error: 403 while accessing https://github.com/eskerda/pybikes.git/info/refs`

something I have overlooked or do I need to be first a Collaborator of this Project?

**Comment by eskerda** [comment]
To do a PR through github, you must fork the repo into your own account, work changes there and then ,once pushed to your repo, all the PR buttons should be there.

https://help.github.com/articles/fork-a-repo/
https://help.github.com/articles/using-pull-requests/

If that does not work for you, feel free to send me the patch through mail though!

**Comment by BenSto** [comment]
Ok then Im going to fork the repo. Thank you very much for the quick answer!!

**Comment by BenSto** [comment]
closed via #84
