### ISSUE TITLE
bicipalma not responding

### ISSUE THREAD

**Issue by lemieuxs** [eskerda/pybikes#91]
When I try to run unittest_pybikes.py When it gets to bicipalma network the update doesn't work.
However when I query http://api.citybik.es/v2/networks/bicipalma I get a response...

Are you aware of this issue, is it temporary ?

**Comment by eskerda** [comment]
You can see a timestamp of when bicipalma was last updated `2015-10-12T11:21:17.712Z` on the feed.

Unfortunately, it seems even the official map is not working, neither has been for a long time:

This is the feed http://83.36.51.60:8080/eTraffic3 linked at http://bicipalma.palmademallorca.es/portal/BICIPALMA/home.jsp?codResi=9 (MAPA DE LES ESTACIONS)

**Comment by eskerda** [comment]
Nothing we can do here, except maybe investigate alternative ways of getting this info

**Comment by lemieuxs** [comment]
Thx for the fast answer !
