### ISSUE TITLE
Dkvelo is broken

### ISSUE THREAD

**Issue by edumucelli** [eskerda/pybikes#99]
http://www.dkbus.com/cartoV3/libProxyCarto.asp does not respond with data anymore.
However, there is the http://www.dk-velo.fr, which offers dkvelos' data as well, but in a different format. I am wondering if we should wait to see if that is just a instability period, create a new Class inside Veloway or proceed to extract a DKVelo class from it.

**Comment by eskerda** [comment]
This page is still up, except it does not work (it requests to libProxyCarto): http://www.dkbus.com/carto/?rub_code=127, so maybe it will come back.

We can add an extra provider: to keep things organized, it can be added to Veloway and use a "multiclass" data format as [smartbike](https://github.com/eskerda/pybikes/blob/master/pybikes/data/smartbike.json)

**Comment by eskerda** [comment]
Fixed in https://github.com/eskerda/pybikes/pull/136
